// Copy Paste the below code into your transform data, make sure you replace the source location to point to your JSON.

let
    Source = Json.Document(File.Contents("INPUT JSON FILE DATA HERE")),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"table_name", "content"}, {"table_name", "content"}),
    #"Removed Top Rows" = Table.Skip(#"Expanded Column1",15),
    #"Removed Bottom Rows" = Table.RemoveLastN(#"Removed Top Rows",20),
    #"Expanded content" = Table.ExpandListColumn(#"Removed Bottom Rows", "content"),
    #"Expanded content1" = Table.ExpandRecordColumn(#"Expanded content", "content", {"clndr_id", "default_flag", "clndr_name", "proj_id", "base_clndr_id", "last_chng_date", "clndr_type", "day_hr_cnt", "week_hr_cnt", "month_hr_cnt", "year_hr_cnt", "rsrc_private", "clndr_data#(lf)"}, {"content.clndr_id", "content.default_flag", "content.clndr_name", "content.proj_id", "content.base_clndr_id", "content.last_chng_date", "content.clndr_type", "content.day_hr_cnt", "content.week_hr_cnt", "content.month_hr_cnt", "content.year_hr_cnt", "content.rsrc_private", "content.clndr_data#(lf)"}),
    Custom1 = Table.TransformColumnNames(#"Expanded content1", each Text.Replace(_,"content.",""))
in
    Custom1